name: Build
on:
- push

env:
  REGISTRY: ghcr.io
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build & test app
        id: test
        run: |
          make test

      - name: Check
        uses: dominikh/staticcheck-action@v1.3.1

      - name: Scan for Vulnerabilities in Code
        uses: Templum/govulncheck-action@v0.10.1
        with:
          go-version: 1.19
          vulncheck-version: latest
          package: ./...
          fail-on-vuln: true

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile
          config: hadolint.yaml

      - name: Set hash
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/arm64,linux/amd64
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ steps.vars.outputs.sha_short }}
          build-args: VERSION=${{ steps.vars.outputs.sha_short }}
          labels: BUILDDATE=${{ github.event.repository.updated_at}},VERSION=${{ steps.vars.outputs.sha_short }}
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
